### ISSUE TITLE
Ability to pass extra wavefront-proxy .conf rules in PCF tile

### ISSUE THREAD

**Issue by aegershman** [wavefrontHQ/cloud-foundry-release#2]
As a PCF/BOSH operator, in order to reduce overhead operational burden of setting up wavefront integrations using a wavefront-proxy VM, I would like to pass extra configuration to the existing wavefront-proxy [deployed as part of the PCF tile](https://github.com/wavefrontHQ/cloud-foundry-release/blob/master/proxy-bosh-release/jobs/wavefront_proxy/templates/wavefront.conf.erb).

I'm picturing a section within the PCF tile where operators could pass extra params. Although this couldn't be used in _all_ cases (e.g., obviously it couldn't be used to collect metrics for integrations that required telegraph to be *on* the integration VMs), it would allow operators to setup simpler integrations such as the [`github integration`](https://longboard.wavefront.com/integration/github/setup)

Thoughts and feedback very welcome. I only started using wavefront today.

**Comment by vikramraman** [comment]
@aegershman Thanks for raising the issue. FYI, we are working on this. Will be part of the next release of the Wavefront PCF tile.

**Comment by aegershman** [comment]
By the way, I did discover that you can hack with the telegraf binary to be able to run as an application on Cloud Foundry. Not super relevant to this issue, but just figured I'd share: https://github.com/aegershman/telegraf-on-cloudfoundry

**Comment by vikramraman** [comment]
@aegershman Just fyi, this issue is fixed with version 1.0 of our nozzle: https://network.pivotal.io/products/wavefront-nozzle/

The new tile includes support to tweak the proxy configuration: https://docs.pivotal.io/partners/wavefront-nozzle/installing.html#install
