### ISSUE TITLE
Ability to leverage proxy bosh release to monitor vcenter

### ISSUE THREAD

**Issue by xyloman** [wavefrontHQ/cloud-foundry-release#4]
In environments in which we host PCF (PAS and PKS) on vSphere it would be desirable to leverage the ability to have the wavefront proxy to collect and forward metrics about vsphere to wavefront?   We do not necessarily needs this in the PCF tile we would be open for levering the proxy-bosh-release against one of the bosh directors that we already have and fill out the params with an ops file.  The reason that we desire this is in these new PAS and PKS environment we are not managing snowflake VMs.  In fact we are trying to have a mandate where no VM is handled or maintained by a human directly and everything will flow via a pipeline and throw bosh management.  This also would ensure that the operating system in use would be updated and maintained and same version that we are applying toe PKS and PAS.

**Comment by vikramraman** [comment]
@xyloman You can use the top level `build.sh` to build the proxy bosh release. You can then deploy it against a bosh director if you wish. Does that address this issue?
